[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/test"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.environment]
NODE_ENV = "production"
